### ISSUE TITLE
Group Channel/ React-Channel types

### ISSUE THREAD

**Issue by octa-george** [sendbird/sendbird-chat-sample-react#19]
Private group channel: a user can join the chat through an invitation by another user who is already a member of the chatroom.
Public group channel: a user can join the chat without invitation from others.

A normal group channel (default setting) can accommodate up to 100 members and a Supergroup channel can accommodate up to 2000 members and can stretch up to 20K members depending on the sendbird plan.

**Comment by AAPK-code** [comment]
Blocked because of `invite users` functionality doesn't work properly:
`Auth error`
<img width="531" alt="image" src="https://user-images.githubusercontent.com/67925765/172160143-9d050c54-b7e2-4b81-acd3-60a6b725e1a1.png">
